### ISSUE TITLE
[BUG] The root npmcli/fs package (and possibly others) seem to be down

### ISSUE THREAD

**Issue by sam0x17** [npm/fs#3]
Right now if you try https://www.npmjs.com/package/@npmcli/fs you will get one of several errors.

Upgrading packages that use `fs` as a dependency will result in something like this:
```
error Couldn't find package "@npmcli/fs@^1.0.0" required by "cacache@^15.0.5" on the "npm" registry.
```

**Comment by AntoniosBarotsis** [comment]
It works now

**Comment by nlf** [comment]
as noted, this was due to an outage. thanks for looking out though!
