### ISSUE TITLE
npm WARN logfile could not be created: TypeError: fs.withOwnerSync is not a function

### ISSUE THREAD

**Issue by surabhigupta2029** [npm/fs#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am developing an expo app. 

Versions:
- expo sdk : 45.0.0
- node: 16
- react native: 0.68.2

Specs:
- Windows 10 laptop
- VS code

When I run npm start, I see the folllowing error `npm WARN logfile could not be created: TypeError: fs.withOwnerSync is not a function`

I have searched solutions online, but could not find anything that works. 

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.7.0
- Node: 16.15.0
- OS: Windows
- platform: VScode + expo app

**Comment by lukekarrys** [comment]
Thanks for the report! Do you have a `package.json` and/or `package-lock.json` that you're using when you see this error? If you can upload those to this issue, it would help narrow down where this error is coming from and why that method doesn't exist.
