### ISSUE TITLE
[BUG] Breaking change with minor version bump

### ISSUE THREAD

**Issue by christopher-kiss** [npm/fs#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our CI pipeline had node 12.4 installed. We utilise angular which has a dependency on npm/fs.

With the release of the new minor version, when installing angular, it bumps the version of npm/fs from 1.0 to 1.1 since angular didn't lock their version of npm/fs to 1.0.

Because the version bump imposed a new minimum nodejs version of 12.13, this broke our pipeline and required updating node. 

### Expected Behavior

I would expect for minor version bumps to not introduce breaking changes, this should most likely have been flagged as a major version bump.

To be clear: I'm not arguing against us needing to update node, I'm arguing that "minor" version bumps shouldn't include breaking changes.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:

**Comment by akeohanePing** [comment]
If anyone has found a workaround for this, please do share.

**Comment by christopher-kiss** [comment]
Well, there are two solutions.

1. You can update node to a version that falls within fs version range.
2. You can use https://docs.npmjs.com/cli/v8/commands/npm-shrinkwrap to pin the dependency of the dependency.

I've not used shrinkwrap, so have no personal details, but some more documentation if you are interested:
https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/
https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

In our case, we simply bumped the version of node on our build machines and went about our business.

**Comment by benbcai** [comment]
@nlf Is the change on #7 a non-passive change since it no longer supports Node 10?

https://github.com/npm/fs/pull/7/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R39

**Comment by nlf** [comment]
my apologies for this one! both the incident, and the delay in correcting it. i appreciate you folks bringing it to my attention and being patient.

i've deprecated version 1.1.0 of this package and published 1.1.1 with the exact same code, but with the engines field removed from the package.json to reflect how the change should've landed in the first place. i've then restored the engines field in a pull request and version 2.0.0 will be where it gets added back.

as of now, you shouldn't be seeing issues any more. if you do, make sure to update to version 1.1.1
